[project]
name = "tagify-backend"
version = "0.1.0"
description = "Tagify backend API server (FastAPI)"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
  "fastapi[standard]",
  "uvicorn",
  "motor",
  "pymongo",
  "pillow",
  "python-dotenv",
  "minio",
  "httpx",
  "numpy>=2.4.0,<3.0",
  "onnxruntime>=1.23.0,<2.0",
]

[tool.uv]
environments = [
    "sys_platform == 'win32'",
    "sys_platform == 'linux' and platform_machine == 'x86_64'",
    "sys_platform == 'darwin' and platform_machine == 'arm64'",
]

